name: Workflow upload report to Codecov
on: 
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'
jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: mvn prepare-package
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
